### ISSUE TITLE
Beautify Comment == RStudio built-in Shortcut "Reflow Comment"?

### ISSUE THREAD

**Issue by SchmidtPaul** [mwip/beautifyR#13]
Someone on Twitter pointed out that RStudio has a built-in shortcut that seems to do the same thing (?) as *Beautify Comment*. He says it's `Ctrl + Shift + /` but for me it is `Ctrl + Shift + #`. Nevertheless, it does work 😮 

![image](https://user-images.githubusercontent.com/31928213/188150881-0d0c71c7-c3fd-4e53-ba33-e52167fd7813.png)
https://twitter.com/SchmidtPaul1989/status/1565600086742138881

**Comment by mwip** [comment]
Indeed it is similar but not the same. Especially with your recent examples I found the built-in struggles more with inline code. Its advantage is that it properly recognizes the user-specified code margin (which is currently hardcoded to 80 in beautifyR). 

Admittedly, I developed the feature and was later pointed to the built-in by a colleague, too. :sweat_smile:

Thanks for spreading the word though. Really appreciate the tweet :relaxed:
