### ISSUE TITLE
error message after trying to use beautifyR add-in

### ISSUE THREAD

**Issue by jalvarada** [mwip/beautifyR#4]
After installing RStudio and then the package in my new laptop when I try to use the add-in two types of error message appear in the console. By the way, I have installed a weird RStudio version: RStudio v1.2.830-1 Preview (I wanted to use one of the new features).

The first error message is the following:

```
Error in cells[[2]] : subscript out of bounds
In addition: Warning message:
In .Primitive("max")() : no non-missing arguments to max; returning -Inf
```

On my second attempt to use the add-in I get this error:

```
Warning in beautifyR(con_text) :
  Fomatting indicator row 2 (e.g. :----) contains invalid values or is not available
  left alignment assumed for all columns
Error in if (!after) c(values, x) else if (after >= lengx) c(x, values) else c(x[1L:after],  : 
  missing value where TRUE/FALSE needed
```

Do you think the issue is the RStudio version? 

**UPDATE:** I've just tried using the RStudio Version 1.1.456 and I keep getting the same error messages...

**Comment by mwip** [comment]
sorry for letting so much time pass. this might be related to #5 
closing.

**Comment by mwip** [comment]
#5 is fixed. Let me know if this fixed your issues as well.
